// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnxBHk2W8hxIpwVyOkLPwn80lYwtRmII',
    appId: '1:843086124201:web:eb3007999f6038a60585b8',
    messagingSenderId: '843086124201',
    projectId: 'authentication-app-9a384',
    authDomain: 'authentication-app-9a384.firebaseapp.com',
    storageBucket: 'authentication-app-9a384.firebasestorage.app',
    measurementId: 'G-MYCDWV55BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwcqCxs5GRczlaVx1zRkYy8yHd1IBsbh8',
    appId: '1:843086124201:android:7adb30bab59e97c20585b8',
    messagingSenderId: '843086124201',
    projectId: 'authentication-app-9a384',
    storageBucket: 'authentication-app-9a384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbkTfhZkaUid0XiyVv_Ln8WwHwjIoBAqg',
    appId: '1:843086124201:ios:c1980627b5b89b180585b8',
    messagingSenderId: '843086124201',
    projectId: 'authentication-app-9a384',
    storageBucket: 'authentication-app-9a384.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbkTfhZkaUid0XiyVv_Ln8WwHwjIoBAqg',
    appId: '1:843086124201:ios:c1980627b5b89b180585b8',
    messagingSenderId: '843086124201',
    projectId: 'authentication-app-9a384',
    storageBucket: 'authentication-app-9a384.firebasestorage.app',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYnxBHk2W8hxIpwVyOkLPwn80lYwtRmII',
    appId: '1:843086124201:web:8b77d0e30345641e0585b8',
    messagingSenderId: '843086124201',
    projectId: 'authentication-app-9a384',
    authDomain: 'authentication-app-9a384.firebaseapp.com',
    storageBucket: 'authentication-app-9a384.firebasestorage.app',
    measurementId: 'G-V3WLDEY1ZL',
  );
}
